"""
Module 3: Growth Edge Detection for Alicia's Autonomous Analysis System

Purpose:
    Identify where the user's thinking is actively evolving vs stagnating.
    Detect growth edges, dormant threads, and frontier opportunities.

Entry point:
    run_growth_edge_detection() -> dict

Architecture:
    - Uses Anthropic Sonnet API for intelligent analysis
    - Reads from memory/insight database and synthesis notes
    - Appends findings to analysis_insights.md
    - Generates detailed bridge report
"""

import json
import logging
import os
from datetime import datetime, timedelta
from pathlib import Path
from typing import Optional
import anthropic
from dotenv import load_dotenv

from myalicia.skills.bridge_protocol import write_bridge_text
from myalicia.config import config
USER_NAME = config.user.name
USER_HANDLE = config.user.handle


# ============================================================================
# CONFIGURATION
# ============================================================================

load_dotenv()

VAULT_ROOT = config.vault.root
SYNTHESIS_FOLDER = VAULT_ROOT / "Alicia" / "Wisdom" / "Synthesis"
BRIDGE_FOLDER = VAULT_ROOT / "Alicia" / "Bridge"
MEMORY_FOLDER = Path.home() / "alicia" / "memory"

# API Configuration
ANTHROPIC_API_KEY = os.getenv("ANTHROPIC_API_KEY")
SONNET_MODEL = "claude-sonnet-4-20250514"

# Logging
logger = logging.getLogger(__name__)
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s"
)


# ============================================================================
# FILE I/O UTILITIES
# ============================================================================

def read_memory_file(filename: str) -> str:
    """Read a memory file with graceful degradation."""
    filepath = MEMORY_FOLDER / filename
    if not filepath.exists():
        logger.warning(f"Memory file not found: {filepath}")
        return ""
    try:
        return filepath.read_text(encoding="utf-8")
    except Exception as e:
        logger.error(f"Error reading {filename}: {e}")
        return ""


def get_recent_synthesis_notes(days: int = 30, limit: int = 10) -> list[dict]:
    """Get the most recent synthesis notes within the specified number of days."""
    if not SYNTHESIS_FOLDER.exists():
        logger.warning(f"Synthesis folder not found: {SYNTHESIS_FOLDER}")
        return []

    cutoff_time = datetime.now() - timedelta(days=days)
    notes = []

    for filepath in SYNTHESIS_FOLDER.glob("*.md"):
        try:
            mtime = datetime.fromtimestamp(filepath.stat().st_mtime)
            if mtime >= cutoff_time:
                content = filepath.read_text(encoding="utf-8")
                notes.append({
                    "filename": filepath.name,
                    "mtime": mtime,
                    "content": content[:2000]  # First 2000 chars for context
                })
        except Exception as e:
            logger.error(f"Error reading synthesis note {filepath.name}: {e}")

    # Sort by mtime descending, return top limit
    notes.sort(key=lambda x: x["mtime"], reverse=True)
    return notes[:limit]


def append_to_analysis_insights(key: str, data: dict) -> None:
    """Append findings to analysis_insights.md with timestamp and source tag."""
    filepath = MEMORY_FOLDER / "analysis_insights.md"

    # Ensure directory exists
    MEMORY_FOLDER.mkdir(parents=True, exist_ok=True)

    # Prepare entry
    timestamp = datetime.now().isoformat()
    entry = f"""
## {key} - {timestamp}
Source: growth_edge_detection
Data: {json.dumps(data, indent=2)}

"""

    # Append to file
    try:
        if filepath.exists():
            current = filepath.read_text(encoding="utf-8")
            filepath.write_text(current + entry, encoding="utf-8")
        else:
            # Initialize file with header
            header = "# Analysis Insights\n\nAutogenerated by Alicia's Autonomous Analysis System\n"
            filepath.write_text(header + entry, encoding="utf-8")
        logger.info(f"Appended to analysis_insights.md: {key}")
    except Exception as e:
        logger.error(f"Error appending to analysis_insights.md: {e}")


def write_bridge_report(report_content: str) -> str:
    """Write detailed report to Bridge folder.

    Routes through bridge_protocol.write_bridge_text for atomicity +
    INDEX logging. (Was previously a bare `filepath.write_text(...)` —
    the migration also fixes the non-atomic write bug.)
    """
    date_str = datetime.now().strftime("%Y-%m-%d")
    report_filename = f"growth-edge-report-{date_str}.md"
    try:
        filepath = write_bridge_text(report_filename, report_content)
        logger.info(f"Wrote bridge report: {filepath}")
        return str(filepath)
    except Exception as e:
        logger.error(f"Error writing bridge report: {e}")
        return ""


# ============================================================================
# DATA PARSING
# ============================================================================

def parse_insights_scores(insights_content: str) -> dict:
    """
    Parse insights.md for score trends over time.
    Expected format: lines with scores (4-5 = high quality)
    Returns dict with topic counts by score level.
    """
    if not insights_content:
        return {"high_recent": 0, "medium_recent": 0, "low_recent": 0}

    lines = insights_content.split("\n")
    scores = {"5": 0, "4": 0, "3": 0, "2": 0, "1": 0}

    for line in lines:
        for score in scores.keys():
            if f"score: {score}" in line or f"Score: {score}" in line:
                scores[score] += 1

    return {
        "high_recent": scores["5"] + scores["4"],
        "medium_recent": scores["3"],
        "low_recent": scores["2"] + scores["1"],
        "raw_scores": scores
    }


def parse_hot_topics(hot_topics_content: str) -> list[str]:
    """Parse hot_topics.md for current interests."""
    if not hot_topics_content:
        return []

    topics = []
    lines = hot_topics_content.split("\n")

    for line in lines:
        line = line.strip()
        # Look for list items, headers, or topic keywords
        if line.startswith(("-", "*", "#")) and line.strip():
            # Extract text without markdown markers
            text = line.lstrip("-*# ").strip()
            if text and len(text) > 2:
                topics.append(text)

    return topics[:10]  # Top 10


def parse_concepts(concepts_content: str) -> list[str]:
    """Parse concepts.md for concepts being developed."""
    if not concepts_content:
        return []

    concepts = []
    lines = concepts_content.split("\n")

    for line in lines:
        line = line.strip()
        # Look for concept definitions or headers
        if line.startswith(("-", "*", "#")) or ":" in line:
            text = line.lstrip("-*# ").strip()
            if text and len(text) > 2:
                concepts.append(text)

    return concepts[:15]  # Top 15


# ============================================================================
# ANTHROPIC API INTEGRATION
# ============================================================================

def analyze_with_sonnet(
    thinking_patterns: str,
    insights_analysis: dict,
    hot_topics: list[str],
    developed_concepts: list[str],
    synthesis_themes: str,
) -> dict:
    """
    Send analysis data to Sonnet for intelligent processing.
    Returns dict with growth edges, dormant threads, and suggested prompts.
    """
    if not ANTHROPIC_API_KEY:
        logger.error("ANTHROPIC_API_KEY not set")
        return {
            "growth_edges": [],
            "dormant_threads": [],
            "suggested_prompts": [],
            "error": "API key not configured"
        }

    client = anthropic.Anthropic(api_key=ANTHROPIC_API_KEY, max_retries=5)

    # Prepare analysis prompt
    prompt_text = f"""You are analyzing {USER_NAME}'s intellectual growth and thinking evolution.

CURRENT THINKING PATTERNS:
{thinking_patterns[:1000] if thinking_patterns else "No pattern data available"}

RECENT INSIGHT SCORES:
- High-scoring (4-5): {insights_analysis.get('high_recent', 0)} insights
- Medium (3): {insights_analysis.get('medium_recent', 0)} insights
- Low (1-2): {insights_analysis.get('low_recent', 0)} insights

CURRENT HOT TOPICS (Active Interests):
{chr(10).join(f"- {topic}" for topic in hot_topics[:8])}

DEVELOPED CONCEPTS (Existing Knowledge):
{chr(10).join(f"- {concept}" for concept in developed_concepts[:10])}

RECENT SYNTHESIS THEMES:
{synthesis_themes[:1500] if synthesis_themes else "No synthesis data available"}

ANALYSIS TASK:
1. Identify 2-4 GROWTH EDGES: Areas where {USER_NAME}'s thinking is actively evolving and expanding.
   - Where are novel insights emerging?
   - What connections are being made?
   - Which hot topics are NEW or underexplored in developed concepts?

2. Identify 2-4 DORMANT THREADS: Topics that were previously hot but have gone quiet.
   - What used to generate insights but isn't currently?
   - Are there abandoned exploration areas?

3. Suggest 3-5 FRONTIER PROMPTS that could open growth edges further.
   - Concrete, specific prompts that push existing edges
   - Should challenge and expand current thinking

Format your response as JSON with keys:
{{
  "growth_edges": [
    {{"area": "...", "evidence": "...", "why_expanding": "..."}},
    ...
  ],
  "dormant_threads": [
    {{"area": "...", "was_hot_because": "...", "reason_dormant": "..."}},
    ...
  ],
  "frontier_prompts": [
    "Specific, actionable prompt...",
    ...
  ],
  "analysis_summary": "2-3 sentence summary of overall intellectual trajectory"
}}"""

    try:
        message = client.messages.create(
            model=SONNET_MODEL,
            max_tokens=2000,
            messages=[
                {"role": "user", "content": prompt_text}
            ]
        )

        response_text = message.content[0].text

        # Parse JSON from response
        try:
            # Find JSON block in response
            start_idx = response_text.find("{")
            end_idx = response_text.rfind("}") + 1
            if start_idx >= 0 and end_idx > start_idx:
                json_str = response_text[start_idx:end_idx]
                return json.loads(json_str)
        except json.JSONDecodeError:
            logger.error(f"Failed to parse JSON from Sonnet response")
            return {
                "growth_edges": [],
                "dormant_threads": [],
                "frontier_prompts": [],
                "raw_response": response_text,
                "error": "JSON parsing failed"
            }

    except Exception as e:
        logger.error(f"Anthropic API error: {e}")
        return {
            "growth_edges": [],
            "dormant_threads": [],
            "frontier_prompts": [],
            "error": str(e)
        }


# ============================================================================
# REPORT GENERATION
# ============================================================================

def generate_bridge_report(
    analysis_result: dict,
    insights_analysis: dict,
    hot_topics: list[str],
    synthesis_notes: list[dict]
) -> str:
    """Generate detailed markdown report for the Bridge folder."""

    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    date_str = datetime.now().strftime("%Y-%m-%d")

    report = f"""# Growth Edge Analysis Report
**Date:** {timestamp}

## Executive Summary
{analysis_result.get('analysis_summary', 'Analysis summary not available')}

---

## Growth Edges (Active Expansion Areas)
Where {USER_NAME}'s thinking is actively evolving:

"""

    if analysis_result.get("growth_edges"):
        for i, edge in enumerate(analysis_result["growth_edges"], 1):
            report += f"""
### {i}. {edge.get('area', 'Unknown')}
- **Evidence:** {edge.get('evidence', 'N/A')}
- **Why Expanding:** {edge.get('why_expanding', 'N/A')}
"""
    else:
        report += "\nNo growth edges identified in current analysis.\n"

    report += "\n---\n\n## Dormant Threads (Previously Hot, Now Quiet)\n"

    if analysis_result.get("dormant_threads"):
        for i, thread in enumerate(analysis_result["dormant_threads"], 1):
            report += f"""
### {i}. {thread.get('area', 'Unknown')}
- **Was Hot Because:** {thread.get('was_hot_because', 'N/A')}
- **Reason for Dormancy:** {thread.get('reason_dormant', 'N/A')}
"""
    else:
        report += "\nNo dormant threads identified.\n"

    report += f"""
---

## Frontier Prompts (To Open Growth Edges Further)
These prompts could deepen and expand current thinking edges:

"""

    if analysis_result.get("frontier_prompts"):
        for i, prompt in enumerate(analysis_result["frontier_prompts"], 1):
            report += f"{i}. {prompt}\n\n"
    else:
        report += "No frontier prompts generated.\n\n"

    report += f"""
---

## Context Snapshot
**Analysis Date:** {date_str}

### Insight Scores (Recent)
- High-scoring (4-5 stars): {insights_analysis.get('high_recent', 0)}
- Medium (3 stars): {insights_analysis.get('medium_recent', 0)}
- Low (1-2 stars): {insights_analysis.get('low_recent', 0)}

### Current Hot Topics
{chr(10).join(f"- {topic}" for topic in hot_topics[:8])}

### Recent Synthesis Activity
{len(synthesis_notes)} synthesis notes reviewed from past 30 days:
"""

    for note in synthesis_notes[:5]:
        report += f"- {note['filename']} ({note['mtime'].strftime('%Y-%m-%d')})\n"

    report += """
---

## Methodology
This analysis uses:
1. Score trend analysis from insights database
2. Current interests (hot_topics.md)
3. Concept development progress (concepts.md)
4. Recent synthesis notes (past 30 days)
5. Sonnet LLM analysis to identify patterns and trajectories

Generated by: Alicia Autonomous Analysis System (Module 3)
"""

    return report


# ============================================================================
# MAIN ENTRY POINT
# ============================================================================

def run_growth_edge_detection() -> dict:
    """
    Main entry point for growth edge detection analysis.

    Returns:
        dict with keys:
            - status: "success" or "error"
            - growth_edges: list of identified growth edges
            - dormant_threads: list of dormant topics
            - suggested_prompts: list of frontier prompts
            - report_path: path to generated bridge report
            - timestamp: ISO timestamp of analysis
            - details: additional analysis details
    """

    logger.info("=" * 70)
    logger.info("Starting Growth Edge Detection (Module 3)")
    logger.info("=" * 70)

    start_time = datetime.now()
    timestamp = start_time.isoformat()

    # Step 1: Read memory files
    logger.info("Reading memory files...")
    patterns_content = read_memory_file("patterns.md")
    insights_content = read_memory_file("insights.md")
    hot_topics_content = read_memory_file("hot_topics.md")
    concepts_content = read_memory_file("concepts.md")

    # Step 2: Parse insights for score trends
    logger.info("Analyzing insight scores...")
    insights_analysis = parse_insights_scores(insights_content)
    logger.info(
        f"Insight summary: {insights_analysis['high_recent']} high, "
        f"{insights_analysis['medium_recent']} medium, "
        f"{insights_analysis['low_recent']} low"
    )

    # Step 3: Parse hot topics and concepts
    logger.info("Extracting hot topics and concepts...")
    hot_topics = parse_hot_topics(hot_topics_content)
    concepts = parse_concepts(concepts_content)
    logger.info(f"Found {len(hot_topics)} hot topics, {len(concepts)} concepts")

    # Step 4: Get recent synthesis notes
    logger.info("Reading recent synthesis notes...")
    synthesis_notes = get_recent_synthesis_notes(days=30, limit=10)
    synthesis_themes = "\n".join(
        f"- {note['filename']}: {note['content'][:200]}"
        for note in synthesis_notes
    )
    logger.info(f"Read {len(synthesis_notes)} synthesis notes")

    # Step 5: Send to Sonnet for analysis
    logger.info("Sending to Sonnet for analysis...")
    analysis_result = analyze_with_sonnet(
        thinking_patterns=patterns_content,
        insights_analysis=insights_analysis,
        hot_topics=hot_topics,
        developed_concepts=concepts,
        synthesis_themes=synthesis_themes,
    )

    if "error" in analysis_result and not analysis_result.get("growth_edges"):
        logger.error(f"Analysis failed: {analysis_result.get('error')}")
        return {
            "status": "error",
            "error": analysis_result.get("error"),
            "timestamp": timestamp,
            "growth_edges": [],
            "dormant_threads": [],
            "suggested_prompts": []
        }

    # Step 6: Generate bridge report
    logger.info("Generating bridge report...")
    report_content = generate_bridge_report(
        analysis_result,
        insights_analysis,
        hot_topics,
        synthesis_notes
    )
    report_path = write_bridge_report(report_content)

    # Step 7: Append to analysis_insights.md
    logger.info("Appending findings to analysis_insights.md...")
    append_to_analysis_insights("growth_edge", {
        "timestamp": timestamp,
        "growth_edges_count": len(analysis_result.get("growth_edges", [])),
        "dormant_threads_count": len(analysis_result.get("dormant_threads", [])),
        "frontier_prompts_count": len(analysis_result.get("frontier_prompts", [])),
        "report_path": report_path
    })

    # Step 8: Compile return dict
    elapsed = (datetime.now() - start_time).total_seconds()
    logger.info(f"Analysis complete in {elapsed:.1f}s")

    return {
        "status": "success",
        "timestamp": timestamp,
        "growth_edges": analysis_result.get("growth_edges", []),
        "dormant_threads": analysis_result.get("dormant_threads", []),
        "suggested_prompts": analysis_result.get("frontier_prompts", []),
        "analysis_summary": analysis_result.get("analysis_summary", ""),
        "report_path": report_path,
        "insights_analyzed": {
            "high_score_count": insights_analysis["high_recent"],
            "medium_score_count": insights_analysis["medium_recent"],
            "low_score_count": insights_analysis["low_recent"]
        },
        "data_sources": {
            "hot_topics_count": len(hot_topics),
            "concepts_count": len(concepts),
            "synthesis_notes_count": len(synthesis_notes)
        },
        "execution_time_seconds": elapsed
    }


# ============================================================================
# CLI SUPPORT
# ============================================================================

if __name__ == "__main__":
    result = run_growth_edge_detection()
    print("\n" + "=" * 70)
    print("GROWTH EDGE DETECTION RESULTS")
    print("=" * 70)
    print(json.dumps(result, indent=2, default=str))
    print(f"\nReport saved to: {result.get('report_path', 'N/A')}")
